### ISSUE TITLE
Unable to install app

### ISSUE THREAD

**Issue by fulljackz** [KOBUGE-Games/Ninja-Training#2]
Hi,

I tried to install the game on my device from fdroid and installation returns 

```
Installation failed due to unknown error
```

I do not have any google services running in the background, is this a problem ?
Is there any way to troubleshoot ? Get a log or anything else ?

Cheers

**Comment by bojidar-bg** [comment]
This should be a missing keystore issue, @alketii.

**Comment by bojidar-bg** [comment]
@fulljackz - Can you run ADT and catlogger, to see the exact error message (might help).

**Comment by fulljackz** [comment]
Here are some outputs from android studio 

```
09-16 13:02:09.992    370-16414/? I/ActivityManager﹕ START {act=android.intent.action.INSTALL_PACKAGE dat=file:///data/data/org.fdroid.fdroid/cache/temp/org.kobuge.ninjatraining_2.apk cmp=com.android.packageinstaller/.PackageInstallerActivity (has extras) u=0} from pid 23914
09-16 13:02:12.626  23800-23800/? I/PackageInstaller﹕ downloaded app uri=file:///data/data/org.fdroid.fdroid/cache/temp/org.kobuge.ninjatraining_2.apk
09-16 13:02:12.628      370-380/? I/ActivityManager﹕ START {dat=file:///data/data/org.fdroid.fdroid/cache/temp/org.kobuge.ninjatraining_2.apk flg=0x2000000 cmp=com.android.packageinstaller/.InstallAppProgress (has extras) u=0} from pid 23800
09-16 13:02:12.746      370-391/? W/ActivityManager﹕ No content provider found for permission revoke: file:///data/data/org.fdroid.fdroid/cache/temp/org.kobuge.ninjatraining_2.apk 
09-16 13:02:14.208      370-391/? E/VoldConnector﹕ NDC Command {119 asec create smdl2tmp1 28 ext4 16aae3a67ff59c9273a266bf3d306d7a 10063 1} took too long (1355ms) 
09-16 13:02:23.153  23817-23828/? I/DefContainer﹕ Copied /data/data/org.fdroid.fdroid/cache/temp/org.kobuge.ninjatraining_2.apk to /mnt/asec/smdl2tmp1/pkg.apk 09-16 13:02:24.431  23817-23828/? E/DefContainer﹕ Could not copy native libraries to /mnt/asec/smdl2tmp1/lib
09-16 13:02:25.816      370-391/? E/VoldConnector﹕ NDC Command {121 asec destroy smdl2tmp1 force} took too long (1301ms) 
09-16 13:02:25.817      370-391/? W/ActivityManager﹕ No content provider found for permission revoke: file:///data/data/org.fdroid.fdroid/cache/temp/org.kobuge.ninjatraining_2.apk
09-16 13:02:25.954  23914-23914/? E/AppDetails﹕ Installer aborted with errorCode: 2
09-16 13:02:26.226  23800-23800/? E/ActivityThread﹕ Activity com.android.packageinstaller.InstallAppProgress has leaked IntentReceiver com.android.packageinstaller.InstallAppProgress$4@417d3a08 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.android.packageinstaller.InstallAppProgress has leaked IntentReceiver com.android.packageinstaller.InstallAppProgress$4@417d3a08 that was originally registered here. Are you missing a call to unregisterReceiver()?
            at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:822)
            at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:593)
            at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1201)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1188)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1182)
            at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:365)
            at com.android.packageinstaller.InstallAppProgress.initView(InstallAppProgress.java:267)
            at com.android.packageinstaller.InstallAppProgress.onCreate(InstallAppProgress.java:179)
            at android.app.Activity.performCreate(Activity.java:5020)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5037)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)
```

Hope this will help !

**Comment by bojidar-bg** [comment]
@fulljackz That's seems to be a strange issue.... That's the best I've found: http://stackoverflow.com/questions/11550798/android-no-content-provider-found-for-permission-revoke :smile:

**Comment by alketii** [comment]
@fulljackz idk, it looks like f-droid error, im not sure, but you can try to download the github release https://github.com/KOBUGE-Games/Ninja-Training/releases/download/v1.0.1/ninja_training.apk so we know for sure.

Thanks.

**Comment by est31** [comment]
Best you file a report for the [f-droid client](https://gitlab.com/fdroid/fdroidclient/issues), they may know more than us.

**Comment by est31** [comment]
Note: this seems to be indeed an [fdroidclient issue](https://gitlab.com/fdroid/fdroidclient/issues/412).

**Comment by fulljackz** [comment]
OK, it seems to be a fdroid error, I could install and launch the game from the apk released on github.

 I'll give this feed on fdroid support team.

Thanks again,
Cheers
